"""E2E intent-routing tests for ovos-skill-camera.

Auto-generated by tools/gen_ovoscope_tests.py
Run: pytest test/end2end/ -v
"""
from unittest import TestCase

from ovos_bus_client.message import Message
from ovos_bus_client.session import Session
from ovos_spec_tools import SpecMessage
from ovoscope import End2EndTest, get_minicroft

SKILL_ID = "ovos-skill-camera.openvoiceos"
LANG = "en-US"


class _IntentRoutingMixin:
    """Shared MiniCroft setup."""

    @classmethod
    def setUpClass(cls):
        cls.minicroft = get_minicroft([SKILL_ID])

    @classmethod
    def tearDownClass(cls):
        if getattr(cls, 'minicroft', None):
            cls.minicroft.stop()


    def _assert_padatious(self, utterance: str, intent_file: str):
        # OVOS-PIPELINE-1 §9.2/§8: the orchestrator broadcasts the generic
        # SpecMessage.INTENT_MATCHED (data.intent_name carries the matched
        # intent), then wraps the per-skill dispatch in the handler-lifecycle
        # trio. The legacy "<skill_id>:<intent>.intent" topic is no longer
        # emitted as the match notification; the dispatch topic itself also
        # drops the ".intent" suffix.
        intent_name = intent_file.removesuffix(".intent")
        intent_msg_type = f"{SKILL_ID}:{intent_name}"
        session = Session(f"e2e-en_us-{intent_file}-{hash(utterance)}")
        session.lang = LANG
        session.pipeline = ["ovos-padatious-pipeline-plugin-high"]
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        test = End2EndTest(
            minicroft=self.minicroft,
            skill_ids=[SKILL_ID],
            eof_msgs=["ovos.utterance.handled"],
            flip_points=["recognizer_loop:utterance"],
            source_message=message,
            activation_points=[str(SpecMessage.INTENT_MATCHED)],
            test_msg_context=False,
            test_message_number=False,
            ignore_messages=[
                str(SpecMessage.SPEAK),
                "recognizer_loop:audio_output_start",
                "recognizer_loop:audio_output_end",
                "mycroft.audio.play_sound",
                # camera PHAL handshake fired from inside the intent handler;
                # not relevant to intent-routing assertions
                "ovos.phal.camera.ping",
                "ovos.phal.camera.get",
            ],
            expected_messages=[
                message,
                Message(f"{SKILL_ID}.activate", {}, {"skill_id": SKILL_ID}),
                Message(str(SpecMessage.INTENT_MATCHED), {}, {"skill_id": SKILL_ID}),
                Message(str(SpecMessage.INTENT_HANDLER_START), {}, {"skill_id": SKILL_ID}),
                Message(intent_msg_type, {}, {"skill_id": SKILL_ID}),
                Message("mycroft.skill.handler.start", {}, {"skill_id": SKILL_ID}),
                Message("mycroft.skill.handler.complete", {}, {"skill_id": SKILL_ID}),
                Message(str(SpecMessage.INTENT_HANDLER_COMPLETE), {}, {"skill_id": SKILL_ID}),
                Message("ovos.utterance.handled", {}, {"skill_id": SKILL_ID}),
            ],
        )
        test.execute(timeout=30)


class TestPadatious1_Have_camera_intent(_IntentRoutingMixin, TestCase):
    """Padatious intent: have_camera.intent"""
    def test_can_i_use_the_camera(self):
        self._assert_padatious(r"can I use the camera", r"have_camera.intent")

    def test_can_you_access_the_camera(self):
        self._assert_padatious(r"can you access the camera", r"have_camera.intent")

    def test_do_you_have_a_camera(self):
        self._assert_padatious(r"do you have a camera", r"have_camera.intent")

    def test_is_a_camera_available(self):
        self._assert_padatious(r"is a camera available", r"have_camera.intent")

    def test_is_the_camera_working(self):
        self._assert_padatious(r"is the camera working", r"have_camera.intent")

class TestPadatious2_Take_picture_intent(_IntentRoutingMixin, TestCase):
    """Padatious intent: take_picture.intent"""
    def test_take_a_photo(self):
        self._assert_padatious(r"take a photo", r"take_picture.intent")

    def test_take_a_picture(self):
        self._assert_padatious(r"take a picture", r"take_picture.intent")

    def test_take_a_selfie(self):
        self._assert_padatious(r"take a selfie", r"take_picture.intent")

    def test_snap_a_photo_of_me(self):
        self._assert_padatious(r"snap a photo of me", r"take_picture.intent")

    def test_use_the_camera_to_take_a_selfie(self):
        self._assert_padatious(r"use the camera to take a selfie", r"take_picture.intent")
